# Generated by Django 3.1.2 on 2020-11-05 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorter', '0005_auto_20201105_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(verbose_name='Запрос')),
                ('error', models.TextField(verbose_name='Ошибка')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 11, 6, 0, 3, 52, 380966))),
            ],
            options={
                'verbose_name': 'Лог ошибки',
                'verbose_name_plural': 'Логи ошибок',
            },
        ),
    ]
